# Generated by Django 2.0.6 on 2019-10-02 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('telefonos1', models.CharField(blank=True, max_length=50, verbose_name='telefono (Fijo)')),
            ],
        ),
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('telefonos1', models.CharField(blank=True, max_length=50, verbose_name='telefono (Fijo)')),
                ('telefonos2', models.CharField(blank=True, max_length=50, verbose_name='telefono (Opcional)')),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('horario', models.CharField(blank=True, max_length=70, verbose_name='Horario de Atencion')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechavencimiento', models.DateField(blank=True, null=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenios.Asesor')),
                ('centromedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenios.CentroMedico')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
