# Generated by Django 2.0.6 on 2019-10-02 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='especialidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='convenios.Especialidad'),
            preserve_default=False,
        ),
    ]
