# Generated by Django 2.0.6 on 2019-10-02 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0002_contrato_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='especialidad',
            name='contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='convenios.Contrato', verbose_name='A quien se la paga la planilla?'),
            preserve_default=False,
        ),
    ]
