# Generated by Django 2.0.6 on 2019-10-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0003_auto_20191002_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fechainicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Convenio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fechavencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
