# Generated by Django 2.0.6 on 2019-10-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0004_auto_20191002_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='asesor',
        ),
        migrations.AddField(
            model_name='asesor',
            name='contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='convenios.Contrato', verbose_name='Contrato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenios.Contrato', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Especialidad'),
        ),
    ]
