# Generated by Django 2.0.6 on 2019-10-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0005_auto_20191002_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='cargo',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
