# Generated by Django 2.0.6 on 2019-10-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0007_auto_20191002_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espe',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AddField(
            model_name='espe',
            name='precio1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='centromedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenios.CentroMedico', verbose_name='Centro Medico'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenios.Espe', verbose_name='Especialidad'),
        ),
    ]
