# Generated by Django 2.0.6 on 2019-10-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0008_auto_20191002_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='correo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
