# Generated by Django 2.0.6 on 2019-10-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0011_auto_20191002_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='estatus',
            field=models.CharField(blank=True, choices=[('A', 'Masculino'), ('P', 'Pendiente'), ('R', 'Retirado')], max_length=12),
        ),
        migrations.AddField(
            model_name='contrato',
            name='observacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
