# Generated by Django 2.0.6 on 2019-03-06 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_auto_20190304_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificaciones',
            options={'verbose_name_plural': 'Configuracion Mensajes Whatsapp'},
        ),
    ]
