# Generated by Django 2.0.6 on 2019-03-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_auto_20190305_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificaciones',
            old_name='mensaje_cobro',
            new_name='mensaje',
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='mensaje_saludo',
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='asunto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='saludo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='tipo',
            field=models.CharField(choices=[('C', 'Cobro'), ('P', 'Promocion')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
