# Generated by Django 2.0.6 on 2019-03-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0006_auto_20190307_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='tipo',
            field=models.CharField(choices=[('C', 'Cobro'), ('P', 'Promocion'), ('D', 'Empresas')], max_length=12),
        ),
    ]
