# Generated by Django 2.0.6 on 2019-03-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0007_auto_20190307_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='tipo',
            field=models.CharField(choices=[('Cobro', 'Cobro'), ('Promocion', 'Promocion'), ('Empresas', 'Empresas')], max_length=12),
        ),
    ]
