# Generated by Django 2.0.6 on 2019-02-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='nombre',
        ),
        migrations.AddField(
            model_name='familia',
            name='documento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
