# Generated by Django 2.0.6 on 2019-03-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaafiliada',
            name='prefijo',
            field=models.CharField(default=57, max_length=2),
        ),
    ]
