# Generated by Django 2.0.6 on 2019-02-18 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0002_auto_20190218_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='tipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='afiliados.TipoDocumento', verbose_name='Tipo de Documento'),
            preserve_default=False,
        ),
    ]
