# Generated by Django 2.0.6 on 2019-02-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0003_familia_tipodoc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresa',
            new_name='EmpresaSeguridadSocial',
        ),
    ]
