# Generated by Django 2.0.6 on 2019-02-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0004_auto_20190218_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresaseguridadsocial',
            options={'verbose_name_plural': 'Empresas Seguridad Social'},
        ),
        migrations.AddField(
            model_name='empresaseguridadsocial',
            name='nombreasesor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre del Asesor'),
        ),
        migrations.AddField(
            model_name='empresaseguridadsocial',
            name='telefonoAsesor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefono del Asesor'),
        ),
    ]
