# Generated by Django 2.0.6 on 2019-02-18 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0005_auto_20190218_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='telefono (Movil)')),
                ('tipoDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliados.TipoDocumento', verbose_name='Tipo de Documento')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresasAfiliada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nit', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
