# Generated by Django 2.0.6 on 2019-02-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0006_empleados_empresasafiliada'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresasafiliada',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefono de la Empresa'),
        ),
    ]
