# Generated by Django 2.0.6 on 2019-02-19 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0007_empresasafiliada_telefono'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpresasAfiliada',
            new_name='EmpresaAfiliada',
        ),
    ]
