# Generated by Django 2.0.6 on 2019-02-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0008_auto_20190218_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
    ]
