# Generated by Django 2.0.6 on 2019-02-19 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0009_auto_20190218_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empresaafiliada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='afiliados.EmpresaAfiliada', verbose_name='Quién realizó el Pago?'),
            preserve_default=False,
        ),
    ]
