# Generated by Django 2.0.6 on 2019-02-19 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0010_empleado_empresaafiliada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
